# Generated by Django 5.0 on 2024-04-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0019_condition_image1_condition_image2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name': 'Информасия о нас  ', 'verbose_name_plural': 'Информасия о нас'},
        ),
        migrations.RemoveField(
            model_name='condition',
            name='title',
        ),
        migrations.AlterField(
            model_name='condition',
            name='descriptions',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
