# Generated by Django 5.0 on 2024-04-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0020_alter_condition_options_remove_condition_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='descriptions2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='letter',
        ),
        migrations.AlterField(
            model_name='news',
            name='descriptions1',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
