# Generated by Django 5.0 on 2024-04-30 02:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_delete_blog_delete_settingsphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='descriptions',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
    ]
