# Generated by Django 5.0 on 2024-04-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_slide_descriptions_alter_slide_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
