# Generated by Django 5.0 on 2024-04-30 02:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_slide_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
