# Generated by Django 5.0 on 2024-04-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_slide_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='descriptions_contacts',
            field=models.TextField(blank=True, null=True, verbose_name="Описание для страницы 'Контакты' "),
        ),
        migrations.AlterField(
            model_name='settings',
            name='descriptions',
            field=models.TextField(verbose_name='Описание сайта'),
        ),
    ]
